parameters:
  
  user_id:
    name: user_id
    in: path
    required: true
    schema:
      type: string
  
  user_id_in_body:
    name: user_id
    in: formData
    required: true
    schema:
      type: string
  
  user_id_in_body_not_required:
    name: user_id
    in: formData
    schema:
      type: string

  service_id:
    name: service_id
    in: path
    required: true
    schema:
      type: integer

  task_id:
    name: task_id
    in: path
    required: true
    schema:
      type: string

  absence_id:
    name: absence_id
    in: path
    required: true
    schema:
      type: string

  absences:
    name: absences
    in: query
    required: true
    schema:
      type: string

  
  date:
    name: date
    in: formData  
    schema:
      type: string
      format: date

  meal:
    name: meal
    in: formData
    schema:
      type: string
      enum: [LUNCH, DINNER]

  name:
    name: name
    in: formData
    schema: 
      type: string

  color:
    name: color
    in: formData
    schema:
      type: string
  
  title:
    name: title
    in: formData
    required: true
    schema:
      type: string
  
  title_not_required:
    name: title
    in: formData
    schema:
      type: string

  category:
    name: category
    in: formData
    required: true
    schema:
      type: integer

  users:
    name: users
    in: formData
    schema:
      type: array
      items:
        type: string




tags:

  - name: Users
    description: User management

  - name: Absences
    description: User absences

  - name: Services
    description: Services

  - name: Tasks
    description: Tasks




definitions:

  User:
    required:
      - _id
      - name
    properties:
      _id:
        type: string
      name:
        type: string
      color:
        type: string
      create_date:
        type: string
        format: date

  Absence:
    required:
      - date
      - meal
    properties:
      user:
        type: string
      date:
        type: string
        format: date
      meal:
        type: string
        enum: ['LUNCH', 'DINNER']
        default: 'LUNCH'

  Service:
    required:
      - title
      - category
    properties:
      title:
        type: string
      category:
        type: integer
      users:
        type: array
        items:
          type: object
          $ref: '#/definitions/Service'

  Task:
    required:
      - user
      - service
      - date
      - meal
    properties:
      user:
        type: string
      service:
        type: string
      date:
        type: string
        format: date
      meal:
        type: string
        enum: ['LUNCH', 'DINNER']
        default: 'LUNCH'